name: Pages

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitlab-ci.yml'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.gitlab-ci.yml'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install app
        run: npm install
      - name: Build app
        run: |
          if [[ -f ./cv.yml ]]; then npm run gen; fi
          ./node_modules/@angular/cli/bin/ng build --prod --base-href="cv" --output-path public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
