name: Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Install app
        run: npm install
      - name: build app
        run: |
          ./node_modules/@angular/cli/bin/ng build --prod --output-path public
